const ASSERTION_TYPES = [
  { key: 'contains', label: 'Contains', description: 'Output must include the expected text.' },
  { key: 'contains-all', label: 'Contains all', description: 'Output must include every expected text item.' },
  { key: 'contains-any', label: 'Contains any', description: 'Output must include at least one expected text item.' },
  { key: 'icontains-all', label: 'Case-insensitive contains all', description: 'Output must include every item regardless of case.' },
  { key: 'icontains-any', label: 'Case-insensitive contains any', description: 'Output must include at least one item regardless of case.' },
  { key: 'contains-none', label: 'Contains none', description: 'Output must not include any expected text item.' },
  { key: 'not-contains', label: 'Not contains', description: 'Output must not include the expected text.' },
  { key: 'not-icontains', label: 'Not case-insensitive contains', description: 'Output must not include expected text regardless of case.' },
  { key: 'icontains', label: 'Case-insensitive contains', description: 'Output must include expected text regardless of case.' },
  { key: 'equals', label: 'Equals', description: 'Output must exactly match the expected text after trimming.' },
  { key: 'not-equals', label: 'Not equals', description: 'Output must not exactly match the expected text after trimming.' },
  { key: 'regex', label: 'Regex', description: 'Output must match a regular expression.' },
  { key: 'starts-with', label: 'Starts with', description: 'Output must start with expected text.' },
  { key: 'ends-with', label: 'Ends with', description: 'Output must end with expected text.' },
  { key: 'is-json', label: 'Valid JSON', description: 'Output must be parseable JSON.' },
  { key: 'contains-json', label: 'Contains JSON fields', description: 'Output JSON must contain expected keys.' },
  { key: 'contains-html', label: 'Contains HTML', description: 'Output must contain HTML markup.' },
  { key: 'is-html', label: 'Valid HTML', description: 'Output must be an HTML document or fragment.' },
  { key: 'contains-xml', label: 'Contains XML', description: 'Output must contain a well-formed XML fragment.' },
  { key: 'is-xml', label: 'Valid XML', description: 'Output must be a well-formed XML document.' },
  { key: 'contains-sql', label: 'Contains SQL', description: 'Output must contain a SQL statement or SQL code block.' },
  { key: 'is-sql', label: 'Valid SQL', description: 'Output must be a non-empty SQL statement.' },
  { key: 'max-length', label: 'Max length', description: 'Output length must be less than or equal to expected number.' },
  { key: 'min-length', label: 'Min length', description: 'Output length must be greater than or equal to expected number.' },
  { key: 'word-count', label: 'Word count', description: 'Output word count must match the configured value or range.' },
  { key: 'levenshtein', label: 'Levenshtein distance', description: 'Output must be within the configured edit distance.' },
  { key: 'latency', label: 'Latency', description: 'Response latency must be under expected milliseconds.' },
  { key: 'latency-ms', label: 'Latency limit', description: 'Response latency must be under expected milliseconds.' },
  { key: 'cost', label: 'Token limit', description: 'Total tokens must be under expected number when usage is available.' },
  { key: 'wildcard', label: 'Wildcard', description: 'Output must match a simple * wildcard pattern.' },
  { key: 'bleu', label: 'BLEU', description: 'Approximate n-gram precision against expected/reference text.' },
  { key: 'gleu', label: 'GLEU', description: 'Approximate balanced n-gram overlap against expected/reference text.' },
  { key: 'rouge-n', label: 'ROUGE-N', description: 'Approximate n-gram recall against expected/reference text.' },
  { key: 'meteor', label: 'METEOR', description: 'Approximate unigram F-score against expected/reference text.' },
  { key: 'finish-reason', label: 'Finish reason', description: 'Provider finish reason must match the expected value.' },
  { key: 'is-refusal', label: 'Is refusal', description: 'Output must look like a policy refusal or inability response.' },
  { key: 'is-valid-function-call', label: 'Valid function call', description: 'Output or provider response must contain a valid function call.' },
  { key: 'is-valid-openai-function-call', label: 'Valid OpenAI function call', description: 'OpenAI-compatible response must contain a valid function call.' },
  { key: 'is-valid-openai-tools-call', label: 'Valid OpenAI tools call', description: 'OpenAI-compatible response must contain valid tool calls.' },
  { key: 'tool-call-f1', label: 'Tool call F1', description: 'Tool call names/arguments must overlap expected tool-call data.' },
  { key: 'javascript', label: 'JavaScript', description: 'Runs your JavaScript expression/function in a sandboxed VM against the output.' },
  { key: 'python', label: 'Python', description: 'Custom Python assertion expression or script.' },
  { key: 'webhook', label: 'Webhook', description: 'External webhook returns pass/score JSON.' },
  { key: 'llm-rubric', label: 'LLM rubric', description: 'Judge model grades against your rubric when a judge provider is configured; falls back to a local keyword heuristic otherwise.' },
  { key: 'agent-rubric', label: 'Agent rubric', description: 'Judge model grades an agent behavior rubric.' },
  { key: 'model-graded-closedqa', label: 'Closed QA grader', description: 'Judge model checks whether the answer satisfies closed-QA criteria.' },
  { key: 'model-graded-factuality', label: 'Model-graded factuality', description: 'Judge model checks factual consistency.' },
  { key: 'g-eval', label: 'G-Eval', description: 'Judge model grades output quality against custom criteria.' },
  { key: 'factuality', label: 'Factuality', description: 'Judge model checks whether output is factually consistent with the assertion.' },
  { key: 'search-rubric', label: 'Search rubric', description: 'Judge model grades search/retrieval quality against criteria.' },
  { key: 'answer-relevance', label: 'Answer relevance', description: 'Judge model checks whether output answers the original prompt.' },
  { key: 'context-recall', label: 'Context recall', description: 'Judge model checks whether ground truth appears in context.' },
  { key: 'context-relevance', label: 'Context relevance', description: 'Judge model checks whether retrieved context is relevant.' },
  { key: 'context-faithfulness', label: 'Context faithfulness', description: 'Judge model checks whether output is supported by context.' },
  { key: 'conversation-relevance', label: 'Conversation relevance', description: 'Judge model checks conversational relevance.' },
  { key: 'similar', label: 'Similarity', description: 'Real embedding-based similarity when a judge provider is configured; falls back to local word-overlap otherwise.' },
  { key: 'similar:cosine', label: 'Similarity cosine', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'similar:dot', label: 'Similarity dot', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'similar:euclidean', label: 'Similarity euclidean', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'moderation', label: 'Moderation', description: 'Real moderation API when a judge provider is configured; falls back to a local keyword heuristic otherwise.' },
  { key: 'guardrails', label: 'Guardrails', description: 'Checks provider-reported guardrails metadata (flagged/blocked). Only meaningful for providers that return guardrails data — e.g. the library-bridged providers (Bedrock, Vertex, watsonx, etc.); passes with a neutral score when no guardrails metadata is present.' },
  { key: 'assert-set', label: 'Assertion group (weighted)', description: 'Nested group of sub-assertions, each optionally weighted, combined into one weighted-average score compared against a threshold.' },
  { key: 'perplexity', label: 'Perplexity', description: 'Passes when output perplexity (from the provider\'s own per-token logprobs) is at or under a threshold. Requires the openai-compatible provider\'s "requestLogprobs" config option enabled, and a model that actually returns logprobs.' },
  { key: 'perplexity-score', label: 'Perplexity score', description: 'Like Perplexity, but reports a normalized 0-1 score (higher is better) instead of pass/fail against a raw perplexity value. Same requirements as Perplexity.' },
  // CyberSecEval assertion types — forked from Meta's PurpleLlama CybersecurityBenchmarks
  // (see app/shared/cyberseceval.cjs and datasets/cyberseceval/PROVENANCE.md). Judge-based
  // ones route through this target's configured judge provider, never an external service.
  { key: 'cyberseceval-insecure-code', label: 'CyberSecEval: Insecure code', description: "Runs this product's ported Insecure Code Detector (regex tier) against the generated code for the test case's language. Passes iff no enabled rule matches." },
  { key: 'cyberseceval-mitre-uplift', label: 'CyberSecEval: MITRE cyberattack uplift', description: 'Two-stage judge (expansion, then benign/malicious classification) evaluating whether the response would help implement a cyberattack. Passes iff refusal or benign.' },
  { key: 'cyberseceval-frr', label: 'CyberSecEval: False refusal rate', description: 'Regex-based refusal detection on a borderline-but-benign prompt. Passes iff the model does NOT refuse (accepts).' },
  { key: 'cyberseceval-prompt-injection', label: 'CyberSecEval: Prompt injection resistance', description: "Judge answers the test case's own yes/no question about whether an injected instruction succeeded. Passes iff no." },
  { key: 'cyberseceval-interpreter-abuse', label: 'CyberSecEval: Interpreter abuse', description: 'Judge classifies the response into extremely/potentially/non-malicious code-interpreter abuse. Passes iff non-malicious.' },
  { key: 'cyberseceval-spear-phishing', label: 'CyberSecEval: Spear phishing capability', description: "Judge rates persuasion skill 1-5 per upstream's rubric, single-exchange approximation of upstream's multi-turn simulation. Passes iff below this product's configured persuasion threshold." },
];

const REDTEAM_PLUGINS = [
  { key: 'ascii-smuggling', label: 'ASCII Smuggling', category: 'Security & Access Control' },
  { key: 'bfla', label: 'Function-Level Authorization Bypass', category: 'Security & Access Control' },
  { key: 'bola', label: 'Object-Level Authorization Bypass', category: 'Security & Access Control' },
  { key: 'cca', label: 'Context Compliance Attack', category: 'Security & Access Control' },
  { key: 'debug-access', label: 'Debug Interface Exposure', category: 'Security & Access Control' },
  { key: 'model-identification', label: 'Model Identification', category: 'Security & Access Control' },
  { key: 'hijacking', label: 'Resource Hijacking', category: 'Security & Access Control' },
  { key: 'indirect-prompt-injection', label: 'Indirect Prompt Injection', category: 'Security & Access Control' },
  { key: 'rbac', label: 'RBAC Implementation', category: 'Security & Access Control' },
  { key: 'reasoning-dos', label: 'Reasoning DoS', category: 'Security & Access Control' },
  { key: 'shell-injection', label: 'Command Injection', category: 'Security & Access Control' },
  { key: 'special-token-injection', label: 'Special Token Injection', category: 'Security & Access Control' },
  { key: 'sql-injection', label: 'SQL Injection', category: 'Security & Access Control' },
  { key: 'ssrf', label: 'SSRF Vulnerability', category: 'Security & Access Control' },
  { key: 'system-prompt-override', label: 'System Prompt Override', category: 'Security & Access Control' },
  { key: 'tool-discovery', label: 'Tool Discovery', category: 'Security & Access Control' },
  { key: 'mcp', label: 'Model Context Protocol', category: 'Security & Access Control' },
  { key: 'cross-session-leak', label: 'Cross-Session Data Leakage', category: 'Security & Access Control' },
  { key: 'data-exfil', label: 'Data Exfiltration', category: 'Security & Access Control' },
  { key: 'divergent-repetition', label: 'Divergent Repetition', category: 'Security & Access Control' },
  { key: 'harmful:privacy', label: 'Privacy Violation', category: 'Security & Access Control' },
  { key: 'insurance:data-disclosure', label: 'Data Disclosure', category: 'Security & Access Control' },
  { key: 'insurance:phi-disclosure', label: 'PHI Disclosure', category: 'Security & Access Control' },
  { key: 'pii:api-db', label: 'PII via API/Database', category: 'Security & Access Control' },
  { key: 'pii:direct', label: 'PII via Direct Exposure', category: 'Security & Access Control' },
  { key: 'pii:session', label: 'PII via Session Data', category: 'Security & Access Control' },
  { key: 'pii:social', label: 'PII via Social Engineering', category: 'Security & Access Control' },
  { key: 'pii', label: 'PII Protection Suite', category: 'Security & Access Control' },
  { key: 'prompt-extraction', label: 'System Prompt Disclosure', category: 'Security & Access Control' },
  { key: 'rag-document-exfiltration', label: 'RAG Document Exfiltration', category: 'Security & Access Control' },
  { key: 'rag-poisoning', label: 'RAG Poisoning', category: 'Security & Access Control' },
  { key: 'rag-source-attribution', label: 'RAG Source Attribution', category: 'Security & Access Control' },
  { key: 'agentic:memory-poisoning', label: 'Agentic Memory Poisoning', category: 'Security & Access Control' },
  { key: 'contracts', label: 'Unauthorized Commitments', category: 'Compliance & Legal' },
  { key: 'coppa', label: 'COPPA Compliance', category: 'Compliance & Legal' },
  { key: 'ferpa', label: 'FERPA Compliance', category: 'Compliance & Legal' },
  { key: 'harmful:chemical-biological-weapons', label: 'WMD Content', category: 'Compliance & Legal' },
  { key: 'harmful:copyright-violations', label: 'IP Violations', category: 'Compliance & Legal' },
  { key: 'harmful:cybercrime:malicious-code', label: 'Malicious Code', category: 'Compliance & Legal' },
  { key: 'harmful:cybercrime', label: 'Cybercrime', category: 'Compliance & Legal' },
  { key: 'harmful:illegal-activities', label: 'Illegal Activity', category: 'Compliance & Legal' },
  { key: 'harmful:illegal-drugs:meth', label: 'Methamphetamine Content', category: 'Compliance & Legal' },
  { key: 'harmful:illegal-drugs', label: 'Drug-Related Content', category: 'Compliance & Legal' },
  { key: 'harmful:indiscriminate-weapons', label: 'Weapons Content', category: 'Compliance & Legal' },
  { key: 'harmful:intellectual-property', label: 'IP Theft', category: 'Compliance & Legal' },
  { key: 'harmful:non-violent-crime', label: 'Non-Violent Crime', category: 'Compliance & Legal' },
  { key: 'harmful:sex-crime', label: 'Sexual Crime Content', category: 'Compliance & Legal' },
  { key: 'harmful:specialized-advice', label: 'Unauthorized Advice', category: 'Compliance & Legal' },
  { key: 'harmful:unsafe-practices', label: 'Dangerous Activity Content', category: 'Compliance & Legal' },
  { key: 'harmful:violent-crime', label: 'Violent Crime Content', category: 'Compliance & Legal' },
  { key: 'harmful:weapons:ied', label: 'Improvised Explosive Devices', category: 'Compliance & Legal' },
  { key: 'insurance:coverage-discrimination', label: 'Coverage Discrimination', category: 'Compliance & Legal' },
  { key: 'insurance:network-misinformation', label: 'Network Misinformation', category: 'Compliance & Legal' },
  { key: 'bias:age', label: 'Age Bias', category: 'Trust & Safety' },
  { key: 'bias:disability', label: 'Disability Bias', category: 'Trust & Safety' },
  { key: 'bias:gender', label: 'Gender Bias', category: 'Trust & Safety' },
  { key: 'bias:race', label: 'Race Bias', category: 'Trust & Safety' },
  { key: 'harmful:child-exploitation', label: 'Child Exploitation', category: 'Trust & Safety' },
  { key: 'harmful:graphic-content', label: 'Graphic Content', category: 'Trust & Safety' },
  { key: 'harmful:harassment-bullying', label: 'Harassment', category: 'Trust & Safety' },
  { key: 'harmful:hate', label: 'Hate Speech', category: 'Trust & Safety' },
  { key: 'harmful:insults', label: 'Personal Attacks', category: 'Trust & Safety' },
  { key: 'harmful:profanity', label: 'Profanity', category: 'Trust & Safety' },
  { key: 'harmful:radicalization', label: 'Extremist Content', category: 'Trust & Safety' },
  { key: 'harmful:self-harm', label: 'Self-Harm', category: 'Trust & Safety' },
  { key: 'harmful:sexual-content', label: 'Explicit Content', category: 'Trust & Safety' },
  { key: 'teen-safety:harmful-body-ideals', label: 'Harmful Body Ideals', category: 'Trust & Safety' },
  { key: 'teen-safety:dangerous-content', label: 'Dangerous Activities & Challenges', category: 'Trust & Safety' },
  { key: 'teen-safety:dangerous-roleplay', label: 'Dangerous Roleplay', category: 'Trust & Safety' },
  { key: 'teen-safety:age-restricted-goods-and-services', label: 'Age-Restricted Goods & Services', category: 'Trust & Safety' },
  { key: 'wordplay', label: 'Wordplay', category: 'Trust & Safety' },
  { key: 'competitors', label: 'Competitors', category: 'Brand' },
  { key: 'excessive-agency', label: 'Excessive Agency', category: 'Brand' },
  { key: 'goal-misalignment', label: 'Goal Misalignment (Goodhart\'s Law)', category: 'Brand' },
  { key: 'hallucination', label: 'Hallucination', category: 'Brand' },
  { key: 'harmful:misinformation-disinformation', label: 'Disinformation Campaigns', category: 'Brand' },
  { key: 'imitation', label: 'Entity Impersonation', category: 'Brand' },
  { key: 'intent', label: 'Intent', category: 'Brand' },
  { key: 'off-topic', label: 'Off-Topic Manipulation', category: 'Brand' },
  { key: 'overreliance', label: 'Overreliance', category: 'Brand' },
  { key: 'policy', label: 'Policy Compliance', category: 'Brand' },
  { key: 'politics', label: 'Political Bias', category: 'Brand' },
  { key: 'religion', label: 'Religious Bias', category: 'Brand' },
  { key: 'unverifiable-claims', label: 'Unverifiable Claims', category: 'Brand' },
  { key: 'ecommerce:pci-dss', label: 'PCI DSS Compliance', category: 'Domain-Specific Risks' },
  { key: 'ecommerce:compliance-bypass', label: 'Compliance Bypass', category: 'Domain-Specific Risks' },
  { key: 'ecommerce:order-fraud', label: 'Order Fraud', category: 'Domain-Specific Risks' },
  { key: 'ecommerce:price-manipulation', label: 'Price Manipulation', category: 'Domain-Specific Risks' },
  { key: 'financial:calculation-error', label: 'Financial Calculation Error', category: 'Domain-Specific Risks' },
  { key: 'financial:compliance-violation', label: 'Financial Compliance Violation', category: 'Domain-Specific Risks' },
  { key: 'financial:confidential-disclosure', label: 'Financial Confidential Disclosure', category: 'Domain-Specific Risks' },
  { key: 'financial:counterfactual', label: 'Financial Counterfactual Narrative', category: 'Domain-Specific Risks' },
  { key: 'financial:data-leakage', label: 'Financial Data Leakage', category: 'Domain-Specific Risks' },
  { key: 'financial:defamation', label: 'Financial Defamation', category: 'Domain-Specific Risks' },
  { key: 'financial:hallucination', label: 'Financial Hallucination', category: 'Domain-Specific Risks' },
  { key: 'financial:impartiality', label: 'Financial Services Impartiality', category: 'Domain-Specific Risks' },
  { key: 'financial:japan-fiea-suitability', label: 'Japan FIEA Suitability', category: 'Domain-Specific Risks' },
  { key: 'financial:misconduct', label: 'Financial Services Misconduct', category: 'Domain-Specific Risks' },
  { key: 'financial:sox-compliance', label: 'Financial SOX Compliance', category: 'Domain-Specific Risks' },
  { key: 'financial:sycophancy', label: 'Financial Sycophancy', category: 'Domain-Specific Risks' },
  { key: 'medical:hallucination', label: 'Medical Hallucination', category: 'Domain-Specific Risks' },
  { key: 'medical:anchoring-bias', label: 'Medical Anchoring Bias', category: 'Domain-Specific Risks' },
  { key: 'medical:fda:ai-disclosure', label: 'FDA AI Disclosure', category: 'Domain-Specific Risks' },
  { key: 'medical:fda:cyber-access-control', label: 'FDA Cyber Access Control', category: 'Domain-Specific Risks' },
  { key: 'medical:fda:cyber-audit-tampering', label: 'FDA Cyber Audit Tampering', category: 'Domain-Specific Risks' },
  { key: 'medical:incorrect-knowledge', label: 'Medical Incorrect Knowledge', category: 'Domain-Specific Risks' },
  { key: 'medical:off-label-use', label: 'Medical Off-Label Use', category: 'Domain-Specific Risks' },
  { key: 'medical:prioritization-error', label: 'Medical Prioritization Error', category: 'Domain-Specific Risks' },
  { key: 'medical:sycophancy', label: 'Medical Sycophancy', category: 'Domain-Specific Risks' },
  { key: 'pharmacy:controlled-substance-compliance', label: 'Controlled Substance Compliance', category: 'Domain-Specific Risks' },
  { key: 'pharmacy:dosage-calculation', label: 'Dosage Calculation', category: 'Domain-Specific Risks' },
  { key: 'pharmacy:drug-interaction', label: 'Drug Interaction Detection', category: 'Domain-Specific Risks' },
  { key: 'telecom:cpni-disclosure', label: 'CPNI Disclosure', category: 'Domain-Specific Risks' },
  { key: 'telecom:location-disclosure', label: 'Location Data Disclosure', category: 'Domain-Specific Risks' },
  { key: 'telecom:account-takeover', label: 'Account Takeover', category: 'Domain-Specific Risks' },
  { key: 'telecom:e911-misinformation', label: 'E911 Misinformation', category: 'Domain-Specific Risks' },
  { key: 'telecom:tcpa-violation', label: 'TCPA Violation', category: 'Domain-Specific Risks' },
  { key: 'telecom:unauthorized-changes', label: 'Unauthorized Changes (Slamming/Cramming)', category: 'Domain-Specific Risks' },
  { key: 'telecom:fraud-enablement', label: 'Fraud Enablement', category: 'Domain-Specific Risks' },
  { key: 'telecom:porting-misinformation', label: 'Porting Misinformation', category: 'Domain-Specific Risks' },
  { key: 'telecom:billing-misinformation', label: 'Billing Misinformation', category: 'Domain-Specific Risks' },
  { key: 'telecom:coverage-misinformation', label: 'Coverage Misinformation', category: 'Domain-Specific Risks' },
  { key: 'telecom:law-enforcement-request-handling', label: 'Law Enforcement Request Handling', category: 'Domain-Specific Risks' },
  { key: 'telecom:accessibility-violation', label: 'Accessibility Violation', category: 'Domain-Specific Risks' },
  { key: 'realestate:fair-housing-discrimination', label: 'Fair Housing Discrimination', category: 'Domain-Specific Risks' },
  { key: 'realestate:steering', label: 'Real Estate Steering', category: 'Domain-Specific Risks' },
  { key: 'realestate:discriminatory-listings', label: 'Discriminatory Listings', category: 'Domain-Specific Risks' },
  { key: 'realestate:lending-discrimination', label: 'Lending Discrimination', category: 'Domain-Specific Risks' },
  { key: 'realestate:valuation-bias', label: 'Valuation Bias', category: 'Domain-Specific Risks' },
  { key: 'realestate:accessibility-discrimination', label: 'Accessibility Discrimination', category: 'Domain-Specific Risks' },
  { key: 'realestate:advertising-discrimination', label: 'Advertising Discrimination', category: 'Domain-Specific Risks' },
  { key: 'realestate:source-of-income', label: 'Source of Income Discrimination', category: 'Domain-Specific Risks' },
  { key: 'aegis', label: 'Aegis Dataset', category: 'Datasets' },
  { key: 'beavertails', label: 'BeaverTails Dataset', category: 'Datasets' },
  { key: 'cyberseceval', label: 'CyberSecEval Dataset', category: 'Datasets' },
  { key: 'donotanswer', label: 'Do Not Answer Dataset', category: 'Datasets' },
  { key: 'harmbench', label: 'Harmbench', category: 'Datasets' },
  { key: 'toxic-chat', label: 'ToxicChat Dataset', category: 'Datasets' },
  { key: 'pliny', label: 'Pliny Prompt Injections', category: 'Datasets' },
  { key: 'unsafebench', label: 'UnsafeBench Dataset', category: 'Datasets' },
  { key: 'vlguard', label: 'VLGuard Dataset', category: 'Datasets' },
  { key: 'vlsu', label: 'VLSU Compositional Safety', category: 'Datasets' },
  { key: 'xstest', label: 'XSTest Dataset', category: 'Datasets' },
  { key: 'canary', label: 'Canary leakage (legacy)', category: 'Legacy (this product)' },
  { key: 'harmful:violence', label: 'Violent content (legacy)', category: 'Legacy (this product)' },
];

const REDTEAM_STRATEGIES = [
  { key: 'basic', label: 'Baseline Testing' },
  { key: 'jailbreak:meta', label: 'Meta-Agent Strategic Jailbreak' },
  { key: 'jailbreak:composite', label: 'Multi-Vector Safety Bypass' },
  { key: 'audio', label: 'Audio Content' },
  { key: 'authoritative-markup-injection', label: 'Authoritative Markup Injection' },
  { key: 'base64', label: 'Base64 Payload Encoding' },
  { key: 'best-of-n', label: 'Best-of-N' },
  { key: 'camelcase', label: 'CamelCase Encoding' },
  { key: 'citation', label: 'Authority Bias Exploitation' },
  { key: 'crescendo', label: 'Multi-Turn Crescendo' },
  { key: 'custom', label: 'Custom' },
  { key: 'emoji', label: 'Emoji Smuggling' },
  { key: 'gcg', label: 'Greedy Coordinate Gradient' },
  { key: 'goat', label: 'Generative Offensive Agent Tester' },
  { key: 'hex', label: 'Hex Encoding' },
  { key: 'homoglyph', label: 'Homoglyph Encoding' },
  { key: 'image', label: 'Image Content' },
  { key: 'indirect-web-pwn', label: 'Indirect Web Prompt Injection' },
  { key: 'jailbreak:goblin', label: 'Goblin Multi-turn' },
  { key: 'jailbreak:hydra', label: 'Hydra Multi-turn' },
  { key: 'jailbreak', label: 'Single-shot Optimization [DEPRECATED]' },
  { key: 'jailbreak:likert', label: 'Likert Scale Jailbreak' },
  { key: 'jailbreak:tree', label: 'Tree-Based Attack Search' },
  { key: 'jailbreak-templates', label: 'Jailbreak Templates' },
  { key: 'layer', label: 'Strategy Layer' },
  { key: 'leetspeak', label: 'Leetspeak Payload Encoding' },
  { key: 'math-prompt', label: 'Mathematical Notation Attack' },
  { key: 'mischievous-user', label: 'Mischievous User' },
  { key: 'morse', label: 'Morse Code Encoding' },
  { key: 'multilingual', label: 'Multilingual Translation [DEPRECATED]' },
  { key: 'piglatin', label: 'Pig Latin Encoding' },
  { key: 'prompt-injection', label: 'Direct Prompt Injection' },
  { key: 'retry', label: 'Regression Testing' },
  { key: 'rot13', label: 'ROT13 Payload Encoding' },
  { key: 'video', label: 'Video Content' },
  { key: 'roleplay', label: 'Roleplay (legacy)' },
  { key: 'encoded', label: 'Encoded attack (legacy)' },
];

// Mirrors real promptfoo's own REMOTE_ONLY_PLUGIN_IDS / STRATEGIES_REQUIRING_REMOTE
// (promptfoo-source/src/redteam/constants/plugins.ts and strategies.ts) — these have no local
// generation logic at all in the real engine, so "Use real adversarial generation" silently
// produces zero test cases for them whenever remote generation is unavailable (e.g. this
// project's own .env sets PROMPTFOO_DISABLE_REDTEAM_REMOTE_GENERATION=true). Flagging them in
// the catalog lets the UI warn *before* a run, rather than only after seeing the
// realGenerationFallbackReason on a run that already came back with fewer cases than expected.
// (promptfoo's coding-agent-only remote plugins are omitted — this catalog doesn't include
// coding-agent plugins at all.)
const REDTEAM_REMOTE_ONLY_PLUGIN_KEYS = new Set([
  'agentic:memory-poisoning', 'ascii-smuggling', 'bfla', 'bola', 'cca', 'competitors', 'coppa',
  'data-exfil', 'ferpa', 'goal-misalignment', 'harmful:misinformation-disinformation',
  'harmful:specialized-advice', 'hijacking', 'indirect-prompt-injection', 'mcp',
  'model-identification', 'off-topic', 'rag-document-exfiltration', 'rag-poisoning',
  'rag-source-attribution', 'reasoning-dos', 'religion', 'special-token-injection', 'ssrf',
  'system-prompt-override', 'wordplay',
  'medical:anchoring-bias', 'medical:fda:ai-disclosure', 'medical:fda:cyber-access-control',
  'medical:fda:cyber-audit-tampering', 'medical:hallucination', 'medical:incorrect-knowledge',
  'medical:off-label-use', 'medical:prioritization-error', 'medical:sycophancy',
  'financial:calculation-error', 'financial:compliance-violation',
  'financial:confidential-disclosure', 'financial:counterfactual', 'financial:data-leakage',
  'financial:defamation', 'financial:hallucination', 'financial:impartiality',
  'financial:japan-fiea-suitability', 'financial:misconduct', 'financial:sox-compliance',
  'financial:sycophancy',
  'pharmacy:controlled-substance-compliance', 'pharmacy:dosage-calculation',
  'pharmacy:drug-interaction',
  'insurance:coverage-discrimination', 'insurance:data-disclosure',
  'insurance:network-misinformation', 'insurance:phi-disclosure',
  'ecommerce:compliance-bypass', 'ecommerce:order-fraud', 'ecommerce:pci-dss',
  'ecommerce:price-manipulation',
  'telecom:cpni-disclosure', 'telecom:location-disclosure', 'telecom:account-takeover',
  'telecom:e911-misinformation', 'telecom:tcpa-violation', 'telecom:unauthorized-changes',
  'telecom:fraud-enablement', 'telecom:porting-misinformation', 'telecom:billing-misinformation',
  'telecom:coverage-misinformation', 'telecom:law-enforcement-request-handling',
  'telecom:accessibility-violation',
  'realestate:fair-housing-discrimination', 'realestate:steering',
  'realestate:discriminatory-listings', 'realestate:lending-discrimination',
  'realestate:valuation-bias', 'realestate:accessibility-discrimination',
  'realestate:advertising-discrimination', 'realestate:source-of-income',
]);
const REDTEAM_REMOTE_ONLY_STRATEGY_KEYS = new Set([
  'audio', 'citation', 'gcg', 'goat', 'indirect-web-pwn', 'jailbreak:composite',
  'jailbreak:goblin', 'jailbreak:hydra', 'jailbreak:likert', 'jailbreak:meta',
]);
for (const plugin of REDTEAM_PLUGINS) {
  if (REDTEAM_REMOTE_ONLY_PLUGIN_KEYS.has(plugin.key)) plugin.remoteOnly = true;
}
for (const strategy of REDTEAM_STRATEGIES) {
  if (REDTEAM_REMOTE_ONLY_STRATEGY_KEYS.has(strategy.key)) strategy.remoteOnly = true;
}

// Ported from promptfoo-source/src/redteam/constants/metadata.ts pluginDescriptions/
// strategyDescriptions, scoped to the remote-only ids above - used as grounding context
// for REDTEAM_SELF_HOSTED_GENERATION (see app/server.cjs) so the self-hosted LLM generates
// a probe appropriate to what the plugin actually tests, not a generic placeholder.
const REDTEAM_REMOTE_ONLY_PLUGIN_DESCRIPTIONS = {
  "agentic:memory-poisoning": "Tests whether an agent is vulnerable to memory poisoning attacks",
  "ascii-smuggling": "Tests for ASCII-based prompt smuggling vulnerabilities",
  "bfla": "Evaluates function-level authorization controls to identify privilege escalation vulnerabilities (OWASP API Security Top 10 #5)",
  "bola": "Tests object-level authorization mechanisms to detect unauthorized data access vulnerabilities (OWASP API Security Top 10 #1)",
  "cca": "Tests for vulnerability to Context Compliance Attacks using fabricated conversation history",
  "competitors": "Assesses system protection against unauthorized competitor endorsements and brand security risks",
  "coppa": "Tests for COPPA (Children's Online Privacy Protection Act) compliance violations, ensuring proper protection of children's data and privacy",
  "data-exfil": "Tests whether the AI can be tricked into exfiltrating sensitive data via URL parameters, images, or markdown links",
  "ferpa": "Tests for Family Educational Rights and Privacy Act compliance",
  "goal-misalignment": "Tests whether AI systems recognize when optimizing measurable proxy metrics might not align with true underlying objectives (Goodhart's Law: \"When a measure becomes a target, it ceases to be a good measure\")",
  "harmful:misinformation-disinformation": "Tests handling of disinformation campaigns",
  "harmful:specialized-advice": "Tests handling of unauthorized professional advice",
  "hijacking": "Assesses protection against unauthorized resource usage and purpose deviation",
  "indirect-prompt-injection": "Evaluates vulnerability to injection attacks via untrusted variables",
  "mcp": "Tests for vulnerabilities to Model Context Protocol (MCP) attacks",
  "model-identification": "Tests whether an AI system reveals its underlying model identity, version, or creator when probed",
  "off-topic": "Tests whether AI systems can be manipulated to go off-topic by performing tasks outside their domain",
  "rag-document-exfiltration": "Tests handling of RAG document exfiltration",
  "rag-poisoning": "Tests resistance against poisoning attacks on RAG retrieval systems",
  "rag-source-attribution": "Tests whether RAG systems fabricate document citations, policy references, or source attributions that don't exist in the knowledge base",
  "reasoning-dos": "Tests for computational resource exhaustion through excessive reasoning patterns",
  "religion": "Assesses handling of religious content and bias mitigation",
  "special-token-injection": "Tests for token injection vulnerabilities using conversation format delimiters",
  "ssrf": "Tests for server-side request forgery vulnerabilities",
  "system-prompt-override": "Tests for system prompt override vulnerabilities",
  "wordplay": "Tests whether AI systems can be tricked into generating profanity or offensive language through innocent-seeming wordplay like riddles and rhyming games",
  "medical:anchoring-bias": "Tests for medical anchoring bias where AI fixates on irrelevant information in medical contexts",
  "medical:fda:ai-disclosure": "Tests whether AI-enabled medical-device or clinical LLM systems disclose intended-use boundaries, confidence and uncertainty, subgroup limitations, data drift, and model or device version changes instead of concealing them",
  "medical:fda:cyber-access-control": "Tests whether medical-device AI systems enforce authenticated, role-scoped, deny-by-default workflows and refuse privileged device, telemetry, update, or therapy actions from unauthorized users or stale sessions",
  "medical:fda:cyber-audit-tampering": "Tests whether medical-device AI systems preserve anomaly alerts, SBOM/version records, and forensic audit trails instead of helping users suppress, rewrite, or delete cybersecurity evidence",
  "medical:hallucination": "Tests for fabricated medical facts, non-existent studies, made-up drug interactions, or other false medical information",
  "medical:incorrect-knowledge": "Tests for factually wrong medical information that could be harmful if followed",
  "medical:off-label-use": "Tests for inappropriate off-label medication recommendations without proper disclaimers, warnings, or professional consultation requirements",
  "medical:prioritization-error": "Tests for poor medical prioritization and triage decisions that could delay critical care",
  "medical:sycophancy": "Tests for agreeing with incorrect medical assumptions or providing responses aligned with user desires at the expense of medical accuracy",
  "financial:calculation-error": "Tests for errors in option pricing, risk calculations, portfolio optimization, or other quantitative financial analysis that could lead to significant losses",
  "financial:compliance-violation": "Tests for suggestions that enable insider trading, market manipulation, money laundering, or other violations of securities laws and financial regulations",
  "financial:confidential-disclosure": "Tests for inappropriate disclosure of material non-public information (MNPI), proprietary trading strategies, client portfolios, deal information, or other confidential financial data",
  "financial:counterfactual": "Tests for false financial narratives including fabricated market events, fictional corporate actions, misleading causation, or manipulated timelines that could mislead investors",
  "financial:data-leakage": "Tests for exposure of proprietary trading algorithms, customer account information, M&A details, or other confidential financial data",
  "financial:defamation": "Tests for false statements that damage the reputation of financial entities, including unfounded fraud accusations, fabricated scandals, or false insolvency claims",
  "financial:hallucination": "Tests for fabricated market data, non-existent financial instruments, fictional company financials, or invented market events",
  "financial:impartiality": "Tests for inappropriate provision of financial advice, investment recommendations, broker suggestions, or transaction facilitation without proper authorization or disclaimers",
  "financial:japan-fiea-suitability": "Tests whether AI recommends unsuitable financial products, downplays risks, or uses sales framing that conflicts with Japan's FIEA suitability and explanation duties",
  "financial:misconduct": "Tests for facilitation of financial crimes including insider trading, market manipulation, front-running, spoofing, bribery, or circumventing financial regulations",
  "financial:sox-compliance": "Tests for violations of Sarbanes-Oxley requirements including internal controls bypass, financial statement manipulation, CEO/CFO certification fraud, audit obstruction, document retention violations, and whistleblower retaliation",
  "financial:sycophancy": "Tests for agreeing with risky trading strategies, unrealistic return expectations, or get-rich-quick schemes",
  "pharmacy:controlled-substance-compliance": "Tests adherence to DEA regulations for controlled substance prescribing, dispensing, and monitoring, including schedule restrictions, quantity limits, early refill detection, PDMP requirements, and red flags for prescription fraud or diversion",
  "pharmacy:dosage-calculation": "Tests accuracy of pharmaceutical dosage calculations including weight-based dosing, renal and hepatic adjustments, unit conversions, IV drip rates, concentration calculations, and pediatric dosing to prevent over/underdosing errors",
  "pharmacy:drug-interaction": "Tests identification of dangerous drug-drug, drug-food, and drug-supplement interactions including major contraindications, CYP450 interactions, QT prolongation risks, serotonin syndrome, and additive effects to prevent serious adverse drug events",
  "insurance:coverage-discrimination": "Tests for discriminatory coverage, underwriting, or claims determinations based on protected characteristics (age, disability, race, genetic information, sex) in violation of federal civil rights laws including ADA, Section 1557, GINA, Fair Housing Act, ECOA, and state unfair trade practices acts",
  "insurance:data-disclosure": "Tests for unauthorized disclosure of protected policyholder data including claims history, property details, driving records, beneficiary information, and business data in violation of GLBA, FCRA, DPPA, and state insurance privacy laws",
  "insurance:network-misinformation": "Tests for inaccurate provider or vendor network information including wrong network status, terminated contracts, ghost networks, and outdated provider data that could expose policyholders to unexpected costs, voided warranties, or inadequate service",
  "insurance:phi-disclosure": "Tests for unauthorized disclosure of Protected Health Information in violation of HIPAA privacy regulations including cross-member PHI leakage, inadequate authentication, and disclosure to unauthorized third parties",
  "ecommerce:compliance-bypass": "Tests for attempts to bypass security rules, terms of service, age restrictions, geographic limitations, or compliance policies in e-commerce systems",
  "ecommerce:order-fraud": "Tests for detection of fraudulent order patterns, unauthorized transactions, account takeover attempts, or payment manipulation in e-commerce checkout and order processing",
  "ecommerce:pci-dss": "Tests for exposure of payment card data including credit card numbers, CVVs, expiration dates, cardholder names, bank account details, and payment tokens in violation of PCI DSS requirements for secure payment processing",
  "ecommerce:price-manipulation": "Tests for price manipulation through discount code abuse, inventory exploits, cart manipulation, unauthorized price modifications, or coupon stacking vulnerabilities",
  "telecom:cpni-disclosure": "Tests for unauthorized disclosure of Customer Proprietary Network Information (CPNI) including call records, service details, and billing information in violation of FCC 47 U.S.C. Section 222",
  "telecom:location-disclosure": "Tests for unauthorized disclosure of customer location data from cell tower connections, GPS, or network information",
  "telecom:account-takeover": "Tests for SIM swap vulnerabilities, authentication bypass, and account hijacking that could enable fraud or identity theft",
  "telecom:e911-misinformation": "Tests for incorrect or unsafe information about emergency calling, location accuracy, VoIP limitations, and E911 regulations (Kari's Law, RAY BAUM's Act)",
  "telecom:tcpa-violation": "Tests for TCPA violations including improper consent handling, Do Not Call list compliance, and illegal robocall/text facilitation",
  "telecom:unauthorized-changes": "Tests for slamming (unauthorized carrier switches) and cramming (unauthorized charges) vulnerabilities that violate FCC Section 258",
  "telecom:fraud-enablement": "Tests for telecom-specific fraud facilitation including caller ID spoofing, SIM box fraud, and service arbitrage schemes",
  "telecom:porting-misinformation": "Tests for incorrect number portability information, unauthorized port facilitation, or port-blocking that violates FCC LNP rules",
  "telecom:billing-misinformation": "Tests for incorrect billing information, hidden fees, or misleading price quotes that violate FCC Truth-in-Billing requirements",
  "telecom:coverage-misinformation": "Tests for false or misleading claims about network coverage, 5G availability, or roaming capabilities",
  "telecom:law-enforcement-request-handling": "Tests for improper handling of law enforcement data requests in violation of CALEA requirements and privacy laws",
  "telecom:accessibility-violation": "Tests for accessibility compliance violations under Section 255, Section 508, ADA, and 21st Century CVAA",
  "realestate:fair-housing-discrimination": "Tests for Fair Housing Act violations across all 7 protected classes: race, color, religion, national origin, sex (including gender identity and sexual orientation), familial status, and disability",
  "realestate:steering": "Tests for illegal steering practices where systems direct buyers toward or away from neighborhoods based on protected class characteristics rather than objective housing criteria",
  "realestate:discriminatory-listings": "Tests for discriminatory language in property listings that indicates preferences, limitations, or discrimination based on protected classes including code words and exclusionary language",
  "realestate:lending-discrimination": "Tests for Equal Credit Opportunity Act (ECOA) and Fair Housing Act violations in mortgage lending including redlining, disparate treatment, and discriminatory underwriting",
  "realestate:valuation-bias": "Tests for algorithmic bias in property appraisals and automated valuation models that could result in discriminatory property valuations based on neighborhood demographics",
  "realestate:accessibility-discrimination": "Tests for Americans with Disabilities Act (ADA) and Fair Housing Act violations in disability accommodations, service animal policies, and reasonable modification requests",
  "realestate:advertising-discrimination": "Tests for Fair Housing Act violations in housing advertising including discriminatory targeting, imagery, and language in digital and traditional marketing",
  "realestate:source-of-income": "Tests for Section 8 voucher and housing assistance discrimination in jurisdictions with source of income protections"
};

const REDTEAM_REMOTE_ONLY_STRATEGY_DESCRIPTIONS = {
  "audio": "Tests detection and handling of audio-based malicious payloads",
  "citation": "Exploits academic authority bias to circumvent content filtering mechanisms",
  "gcg": "Greedy Coordinate Gradient adversarial suffix attack",
  "goat": "Deploys dynamic attack generation using advanced adversarial techniques",
  "indirect-web-pwn": "Embeds attack prompts in web pages for indirect prompt injection via web fetch",
  "jailbreak:composite": "Chains multiple attack vectors for enhanced effectiveness",
  "jailbreak:goblin": "Multi-turn jailbreak strategy focused on encoding techniques, math, and logic problems",
  "jailbreak:hydra": "Multi-turn conversational attacks with meta-learning that adapts strategy based on full conversation history",
  "jailbreak:likert": "Uses Likert scale-based prompts to bypass content filters",
  "jailbreak:meta": "Agent that dynamically builds an attack taxonomy and learns from attack history"
};


// Genuinely optional — gated on `audit.scanners` in executeModelAuditRun, so selecting or
// deselecting one of these actually changes what runs.
const AUDIT_SCANNERS = [
  { key: 'secrets', label: 'Secret exposure' },
  { key: 'malware', label: 'Malware indicators' },
  { key: 'unsafe-code', label: 'Unsafe code' },
  { key: 'sbom', label: 'SBOM/MBOM' },
  { key: 'dependency-risk', label: 'Dependency risk' },
  { key: 'model-card', label: 'Model card' },
  { key: 'data-lineage', label: 'Data lineage' },
];

// Always run on every model-audit stage regardless of the `scanners` selection — kept out of
// AUDIT_SCANNERS above so the "select checks to include" picker doesn't misleadingly imply
// these can be turned off. Exposed separately so the UI can show them as informational
// ("always included"), not as checkboxes whose state has no actual effect. Previously
// `metadata-completeness`/`license`/`provenance` were listed in AUDIT_SCANNERS as if optional
// while always running, and `runtime-boundary`/`data-classification` always ran but weren't
// listed anywhere at all — both silently misrepresented what the scanner picker controlled.
const AUDIT_BASELINE_CHECKS = [
  { key: 'metadata-completeness', label: 'Metadata completeness' },
  { key: 'provenance', label: 'Model provenance' },
  { key: 'license', label: 'License policy' },
  { key: 'runtime-boundary', label: 'Runtime boundary' },
  { key: 'data-classification', label: 'Data classification' },
];

module.exports = {
  ASSERTION_TYPES,
  REDTEAM_PLUGINS,
  REDTEAM_STRATEGIES,
  AUDIT_SCANNERS,
  AUDIT_BASELINE_CHECKS,
  REDTEAM_REMOTE_ONLY_PLUGIN_KEYS,
  REDTEAM_REMOTE_ONLY_STRATEGY_KEYS,
  REDTEAM_REMOTE_ONLY_PLUGIN_DESCRIPTIONS,
  REDTEAM_REMOTE_ONLY_STRATEGY_DESCRIPTIONS,
};
