const ASSERTION_TYPES = [
  { key: 'contains', label: 'Contains', description: 'Output must include the expected text.' },
  { key: 'contains-all', label: 'Contains all', description: 'Output must include every expected text item.' },
  { key: 'contains-any', label: 'Contains any', description: 'Output must include at least one expected text item.' },
  { key: 'icontains-all', label: 'Case-insensitive contains all', description: 'Output must include every item regardless of case.' },
  { key: 'icontains-any', label: 'Case-insensitive contains any', description: 'Output must include at least one item regardless of case.' },
  { key: 'contains-none', label: 'Contains none', description: 'Output must not include any expected text item.' },
  { key: 'not-contains', label: 'Not contains', description: 'Output must not include the expected text.' },
  { key: 'not-icontains', label: 'Not case-insensitive contains', description: 'Output must not include expected text regardless of case.' },
  { key: 'icontains', label: 'Case-insensitive contains', description: 'Output must include expected text regardless of case.' },
  { key: 'equals', label: 'Equals', description: 'Output must exactly match the expected text after trimming.' },
  { key: 'not-equals', label: 'Not equals', description: 'Output must not exactly match the expected text after trimming.' },
  { key: 'regex', label: 'Regex', description: 'Output must match a regular expression.' },
  { key: 'starts-with', label: 'Starts with', description: 'Output must start with expected text.' },
  { key: 'ends-with', label: 'Ends with', description: 'Output must end with expected text.' },
  { key: 'is-json', label: 'Valid JSON', description: 'Output must be parseable JSON.' },
  { key: 'contains-json', label: 'Contains JSON fields', description: 'Output JSON must contain expected keys.' },
  { key: 'contains-html', label: 'Contains HTML', description: 'Output must contain HTML markup.' },
  { key: 'is-html', label: 'Valid HTML', description: 'Output must be an HTML document or fragment.' },
  { key: 'contains-xml', label: 'Contains XML', description: 'Output must contain a well-formed XML fragment.' },
  { key: 'is-xml', label: 'Valid XML', description: 'Output must be a well-formed XML document.' },
  { key: 'contains-sql', label: 'Contains SQL', description: 'Output must contain a SQL statement or SQL code block.' },
  { key: 'is-sql', label: 'Valid SQL', description: 'Output must be a non-empty SQL statement.' },
  { key: 'max-length', label: 'Max length', description: 'Output length must be less than or equal to expected number.' },
  { key: 'min-length', label: 'Min length', description: 'Output length must be greater than or equal to expected number.' },
  { key: 'word-count', label: 'Word count', description: 'Output word count must match the configured value or range.' },
  { key: 'levenshtein', label: 'Levenshtein distance', description: 'Output must be within the configured edit distance.' },
  { key: 'latency', label: 'Latency', description: 'Response latency must be under expected milliseconds.' },
  { key: 'latency-ms', label: 'Latency limit', description: 'Response latency must be under expected milliseconds.' },
  { key: 'cost', label: 'Token limit', description: 'Total tokens must be under expected number when usage is available.' },
  { key: 'wildcard', label: 'Wildcard', description: 'Output must match a simple * wildcard pattern.' },
  { key: 'bleu', label: 'BLEU', description: 'Approximate n-gram precision against expected/reference text.' },
  { key: 'gleu', label: 'GLEU', description: 'Approximate balanced n-gram overlap against expected/reference text.' },
  { key: 'rouge-n', label: 'ROUGE-N', description: 'Approximate n-gram recall against expected/reference text.' },
  { key: 'meteor', label: 'METEOR', description: 'Approximate unigram F-score against expected/reference text.' },
  { key: 'finish-reason', label: 'Finish reason', description: 'Provider finish reason must match the expected value.' },
  { key: 'is-refusal', label: 'Is refusal', description: 'Output must look like a policy refusal or inability response.' },
  { key: 'is-valid-function-call', label: 'Valid function call', description: 'Output or provider response must contain a valid function call.' },
  { key: 'is-valid-openai-function-call', label: 'Valid OpenAI function call', description: 'OpenAI-compatible response must contain a valid function call.' },
  { key: 'is-valid-openai-tools-call', label: 'Valid OpenAI tools call', description: 'OpenAI-compatible response must contain valid tool calls.' },
  { key: 'tool-call-f1', label: 'Tool call F1', description: 'Tool call names/arguments must overlap expected tool-call data.' },
  { key: 'javascript', label: 'JavaScript', description: 'Custom JavaScript assertion placeholder.' },
  { key: 'python', label: 'Python', description: 'Custom Python assertion expression or script.' },
  { key: 'webhook', label: 'Webhook', description: 'External webhook returns pass/score JSON.' },
  { key: 'llm-rubric', label: 'LLM rubric', description: 'Rubric-based grading placeholder.' },
  { key: 'agent-rubric', label: 'Agent rubric', description: 'Judge model grades an agent behavior rubric.' },
  { key: 'model-graded-closedqa', label: 'Closed QA grader', description: 'Judge model checks whether the answer satisfies closed-QA criteria.' },
  { key: 'model-graded-factuality', label: 'Model-graded factuality', description: 'Judge model checks factual consistency.' },
  { key: 'g-eval', label: 'G-Eval', description: 'Judge model grades output quality against custom criteria.' },
  { key: 'factuality', label: 'Factuality', description: 'Judge model checks whether output is factually consistent with the assertion.' },
  { key: 'search-rubric', label: 'Search rubric', description: 'Judge model grades search/retrieval quality against criteria.' },
  { key: 'answer-relevance', label: 'Answer relevance', description: 'Judge model checks whether output answers the original prompt.' },
  { key: 'context-recall', label: 'Context recall', description: 'Judge model checks whether ground truth appears in context.' },
  { key: 'context-relevance', label: 'Context relevance', description: 'Judge model checks whether retrieved context is relevant.' },
  { key: 'context-faithfulness', label: 'Context faithfulness', description: 'Judge model checks whether output is supported by context.' },
  { key: 'conversation-relevance', label: 'Conversation relevance', description: 'Judge model checks conversational relevance.' },
  { key: 'similar', label: 'Similarity', description: 'Semantic similarity grading placeholder.' },
  { key: 'similar:cosine', label: 'Similarity cosine', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'similar:dot', label: 'Similarity dot', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'similar:euclidean', label: 'Similarity euclidean', description: 'Approximate semantic similarity using token overlap.' },
  { key: 'moderation', label: 'Moderation', description: 'Safety moderation grading placeholder.' },
];

const REDTEAM_PLUGINS = [
  { key: 'system-prompt-override', label: 'System prompt override', category: 'Prompt injection' },
  { key: 'indirect-prompt-injection', label: 'Indirect prompt injection', category: 'Prompt injection' },
  { key: 'prompt-extraction', label: 'Prompt extraction', category: 'Secrets and leakage' },
  { key: 'pii:direct', label: 'PII direct disclosure', category: 'Privacy' },
  { key: 'pii:session', label: 'PII session leakage', category: 'Privacy' },
  { key: 'contracts', label: 'Unauthorized contracts', category: 'Policy' },
  { key: 'rbac', label: 'RBAC bypass', category: 'Authorization' },
  { key: 'bfla', label: 'Function-level authorization', category: 'Authorization' },
  { key: 'bola', label: 'Object-level authorization', category: 'Authorization' },
  { key: 'ssrf', label: 'SSRF', category: 'Tool abuse' },
  { key: 'sql-injection', label: 'SQL injection', category: 'Tool abuse' },
  { key: 'shell-injection', label: 'Shell injection', category: 'Tool abuse' },
  { key: 'harmful:hate', label: 'Hate content', category: 'Harmful content' },
  { key: 'harmful:self-harm', label: 'Self-harm content', category: 'Harmful content' },
  { key: 'harmful:violence', label: 'Violent content', category: 'Harmful content' },
  { key: 'excessive-agency', label: 'Excessive agency', category: 'Agent behavior' },
  { key: 'tool-discovery', label: 'Tool discovery', category: 'Agent behavior' },
  { key: 'competitors', label: 'Competitor policy', category: 'Business policy' },
  { key: 'debug-access', label: 'Debug access', category: 'Secrets and leakage' },
  { key: 'canary', label: 'Canary leakage', category: 'Secrets and leakage' },
];

const REDTEAM_STRATEGIES = [
  { key: 'basic', label: 'Basic probing' },
  { key: 'jailbreak', label: 'Jailbreak' },
  { key: 'jailbreak-templates', label: 'Jailbreak templates' },
  { key: 'prompt-injection', label: 'Prompt injection' },
  { key: 'multilingual', label: 'Multilingual' },
  { key: 'roleplay', label: 'Roleplay' },
  { key: 'crescendo', label: 'Multi-turn escalation' },
  { key: 'best-of-n', label: 'Best-of-N' },
  { key: 'composite', label: 'Composite strategy' },
  { key: 'encoded', label: 'Encoded attack' },
];

const AUDIT_SCANNERS = [
  { key: 'metadata-completeness', label: 'Metadata completeness' },
  { key: 'license', label: 'License policy' },
  { key: 'provenance', label: 'Model provenance' },
  { key: 'secrets', label: 'Secret exposure' },
  { key: 'malware', label: 'Malware indicators' },
  { key: 'unsafe-code', label: 'Unsafe code' },
  { key: 'sbom', label: 'SBOM/MBOM' },
  { key: 'dependency-risk', label: 'Dependency risk' },
  { key: 'model-card', label: 'Model card' },
  { key: 'data-lineage', label: 'Data lineage' },
];

module.exports = {
  ASSERTION_TYPES,
  REDTEAM_PLUGINS,
  REDTEAM_STRATEGIES,
  AUDIT_SCANNERS,
};
